// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartOffice;

#nullable disable

namespace SmartOffice.Migrations
{
    [DbContext(typeof(SmartOfficeDbContext))]
    [Migration("20240319135130_SmartOfficeDB")]
    partial class SmartOfficeDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartOffice.Models.RestaurantModels.RestaurantViewModel", b =>
                {
                    b.Property<string>("FoodorderRestaurantIdProp")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RestId");

                    b.Property<string>("FoodorderRestaurantCityProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestCity");

                    b.Property<string>("FoodorderRestaurantDeliveryYesNoProp")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("RestDelivery");

                    b.Property<string>("FoodorderRestaurantLieferandoLinkProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestLieferandoLink");

                    b.Property<string>("FoodorderRestaurantMinimalOrderValueProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestMinOrderValue");

                    b.Property<string>("FoodorderRestaurantNameProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestName");

                    b.Property<string>("FoodorderRestaurantOrdertypeAppTelephoneProp")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("RestAppTelephone");

                    b.Property<string>("FoodorderRestaurantPhonenumberProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestPhonenumber");

                    b.Property<string>("FoodorderRestaurantStreetProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestStreet");

                    b.Property<string>("FoodorderRestaurantTypeProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestType");

                    b.Property<string>("FoodorderRestaurantZipcodeProp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RestZipcode");

                    b.HasKey("FoodorderRestaurantIdProp");

                    b.ToTable("SoRestTab", (string)null);
                });

            modelBuilder.Entity("SmartOffice.Models.UserModels.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("ActivePaypal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaypalEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserPassword")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("SoUserTab", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
